x-veld:
  code:
    about:
      description:
      topics:

    inputs:
      volume: /veld/input/
      file_formats:
        - "csv"
        - "txt"
      contents: 
        - "NLP training data"
        - "NLP data"

    outputs:
      volume: /veld/output/
      file_formats: "word2vec model"
      contents:
        - "NLP model"
        - "word embeddings model"

    environment:
      train_data_path:
        description: "path to training data file"
        type: path
        path_prefix: "/veld/input/"
      train_data_description:
        description: "short human description for the kind of training data"
        type: string
        optional: true
      model_path:
        description: "path to model file"
        type: path
        path_prefix: "/veld/output/"
      training_architecture:
        description: "short label for the overall training setup"
        type: string
      model_id: 
        description: "id for the specific model"
        type: string
      vector_size: 
        description: "word2vec hyperparameter"
        type: int
        default: 500
      window: 
        description: "word2vec hyperparameter"
        type: int
        default: 5
      min_count: 
        description: "word2vec hyperparameter"
        type: int
        default: 5
          
services:
  veld_train:
    build: .
    command: python /veld/code/train.py
    working_dir: /veld/code/
    volumes:
      - ./src/train/:/veld/code/
    environment:
      in_train_data_file: null
      out_model_file: null
      epochs: 100
      vector_size: 500
      window: 5
      min_count: 5


