x-veld:
  code:
    about:
      description:
      topics:

    inputs:
      volume: /veld/input/
      file_formats: "txt"
      contents: 
        - "NLP training data"
        - "NLP data"

    outputs:
      volume: /veld/output/
      file_formats: "word2vec"
      contents:
        - "NLP model"
        - "word embeddings model"

    environment:
      in_train_data_file:
        description: "name of training data file"
        type: file
        volume: /veld/input/
      out_model_file:
        description: "name of model file"
        type: file
        volume: /veld/output/
      epochs: 
        description: "word2vec hyperparameter"
        type: int
        default: 100
      vector_size: 
        description: "word2vec hyperparameter"
        type: int
        default: 300
      window: 
        description: "word2vec hyperparameter"
        type: int
        default: 5
      min_count: 
        description: "word2vec hyperparameter"
        type: int
        default: 3
          
services:
  veld_train:
    build: .
    command: python /veld/code/train.py
    working_dir: /veld/code/
    volumes:
      - ./src/train/:/veld/code/
      - ./data/training_data/:/veld/input/
      - ./data/model/:/veld/output/
    environment:
      in_train_data_file: null
      out_model_file: null
      epochs: 100
      vector_size: 300
      window: 5
      min_count: 3


