x-veld:
  code:
    about:
      description: "inference with a word2vec model, visualising relatedness in a jupyter notebook."
      topics:
        - "NLP"
        - "word embeddings"

    inputs:
      volume: /veld/input/
      file_formats: "word2vec"
      contents:
        - "NLP model"
        - "word embeddings model"

    environment:
      in_model_file:
        description: "path to model file"
        type: file
        volume: /veld/input/
          
services:
  veld_infer:
    build: .
    command: jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password='' --allow-root
    ports:
      - 8888:8888
    working_dir: /veld/code/
    volumes:
      - ./src/infer/:/veld/code/
      - ./data/model/:/veld/input/
    environment:
      in_model_file: null

